# Generated by Django 5.1.1 on 2024-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='product_pro_name_b60cd1_idx')],
            },
        ),
    ]
